Ft verify account 187742590
atlp-rwanda/hackers-ec-Fe pull request #14
Opened 2024-06-16 04:04 UTC by kwizera-bonheur25

#### What does this PR do?
This PR fix the responsiveness of sign up
#### Description of Task to be completed?
- fix the responsivess on mobile SAMSUNG and Iphone 12 and laptop
#### How should this be manually tested?
navigate to to this branch "fix-signup" run npm i and run npm run dev and navigate to register link and test in different devices

#### Screenshots (if appropriate)
<img width="466" alt="Screenshot 2024-06-16 at 06 01 15" src="https://github.com/atlp-rwanda/hackers-ec-Fe/assets/166609330/954e8a74-32eb-40da-8ef3-0a1c5c0c353f">
<img width="431" alt="Screenshot 2024-06-16 at 06 01 29" src="https://github.com/atlp-rwanda/hackers-ec-Fe/assets/166609330/621f5dc2-ddf5-4893-9f30-7637fc6d6ae9">
<img width="1105" alt="Screenshot 2024-06-16 at 06 00 57" src="https://github.com/atlp-rwanda/hackers-ec-Fe/assets/166609330/be6bb558-4168-4024-b530-7c21bbd8957b">

2024-06-17 07:12 UTC, YvetteNyibuka requested changes
You still have some issues with responsiveness

![image](https://github.com/atlp-rwanda/hackers-ec-Fe/assets/107992107/fe362f00-101b-43ab-83d6-505b606604ef)

![image](https://github.com/atlp-rwanda/hackers-ec-Fe/assets/107992107/9c63ed25-0cd6-45ca-b1c0-f59b66cebf43)

fix them first

2024-06-20 10:01 UTC, Hakizimana-Clement commented on src/components/Nav.tsx
> +					<Link to="users/account/verify/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImI0NTIzYjdjLTE2YjAtNDQ2Ni05Zjc4LTFlYmU0OTBiZjg2OSIsInJvbGUiOiIxMWFmZDRmMS0wYmVkLTRhM2ItOGFkNS0wOTc4ZGFiZjhmY2QiLCJpYX
Why do we have this token in this link???????

2024-06-20 10:02 UTC, Hakizimana-Clement commented on src/components/Nav.tsx
> +					<Link to="users/account/verify/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImI0NTIzYjdjLTE2YjAtNDQ2Ni05Zjc4LTFlYmU0OTBiZjg2OSIsInJvbGUiOiIxMWFmZDRmMS0wYmVkLTRhM2ItOGFkNS0wOTc4ZGFiZjhmY2QiLCJpYX
Why do we have this token in this link?????

2024-06-20 10:02 UTC, Hakizimana-Clement commented on src/components/Nav.tsx
> +					<Link to="users/account/verify/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImI0NTIzYjdjLTE2YjAtNDQ2Ni05Zjc4LTFlYmU0OTBiZjg2OSIsInJvbGUiOiIxMWFmZDRmMS0wYmVkLTRhM2ItOGFkNS0wOTc4ZGFiZjhmY2QiLCJpYX
Why do we have this token in this link???????

2024-06-20 10:02 UTC, Hakizimana-Clement commented on src/components/Nav.tsx
> +					<Link to="users/account/verify/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImI0NTIzYjdjLTE2YjAtNDQ2Ni05Zjc4LTFlYmU0OTBiZjg2OSIsInJvbGUiOiIxMWFmZDRmMS0wYmVkLTRhM2ItOGFkNS0wOTc4ZGFiZjhmY2QiLCJpYX
Why do we have this token in this link?????

2024-06-20 11:22 UTC, Hakizimana-Clement approved these changes

2024-06-20 11:31 UTC, Tuyisenge2 approved these changes

2024-06-20 14:02 UTC, leandreAlly requested changes

2024-06-20 14:02 UTC, leandreAlly commented on src/@types/auth/VerifyAccountTypes.ts
> +}
change this into types instead of interface

2024-06-20 14:02 UTC, leandreAlly commented on src/components/auth/VerifyAccount.tsx
> +import { useRef } from 'react';
simply organize this import

2024-06-20 14:02 UTC, leandreAlly commented on src/components/auth/VerifyAccount.tsx
> +		effectRan.current = true;
remove this useRef hook and check if it's working on hosted version

2024-06-20 20:56 UTC, leandreAlly approved these changes

2024-06-20 20:57 UTC, merged