#187419010 A seller should be able to create/add items
atlp-rwanda/hackers-ec-Fe pull request #20
Opened 2024-06-18 05:27 UTC by cyusasnave

### Description
As a Seller
I should be able to add/create items for sale
This page should only be accessible to sellers, i.e authenticated
Such that the stock can be seen by any requesting client
Handle all responses and errors from the backend

### How to test it?

1. Clone the repo and checkout to `feat-create-products-187419010`
2. Run `npm run dev` and go to route `/dashboard/seller/products/new`

### Pivot tracker id

187419010

2024-06-21 12:21 UTC, Angemichel12 approved these changes

2024-06-21 15:00 UTC, Hakizimana-Clement approved these changes

2024-06-22 14:21 UTC, leandreAlly requested changes

2024-06-22 14:21 UTC, leandreAlly commented on package.json
> +		"axios-mock-adapter": "^1.22.0",
check if this library is being or used, if not remove it  "axios-mock-adapter": "^1.22.0",

2024-06-22 14:21 UTC, leandreAlly commented on package.json
> +		"@testing-library/user-event": "^14.5.2",
let's also this be installed as dev dependency: "@testing-library/user-event": "^14.5.2",

2024-06-22 14:21 UTC, leandreAlly commented on package.json
> +		"redux-mock-store": "^1.5.4",
let's this also be installed as dev dependency: "redux-mock-store": "^1.5.4",

2024-06-22 14:21 UTC, leandreAlly commented on package.json
>  		"typical": "^7.1.1",
this library should be removed since it's not being used: "typical": "^7.1.1",

2024-06-22 14:21 UTC, leandreAlly commented on src/@types/Category.tsx
> +}
this file should be .ts since it doesn't contain any jsx code.

2024-06-22 14:38 UTC, leandreAlly approved these changes

2024-06-22 14:38 UTC, merged