#187419011 Product update
atlp-rwanda/hackers-ec-Fe pull request #34
Opened 2024-07-03 15:30 UTC by GarrixA

# What does this do?
- This PR contains the product update and delete
- Only for seller and their own collection
## How to test this
- clone the repo
- navigate my branch
- login a seller
- test edit and delete functionality
### Pivotal tracker id

      #187419011

2024-07-05 15:32 UTC, Angemichel12 commented on src/components/Forms/AddProductForm.tsx
> +	console.log(productData.expiryDate, 'eeeeeeexpiryDate');
Remove this console.log()

2024-07-05 15:33 UTC, Angemichel12 commented on src/components/Forms/AddProductForm.tsx
> +	console.log(productData, 'Proooooooddddd');
remove this console.log()

2024-07-06 14:56 UTC, Angemichel12 approved these changes

2024-07-07 07:35 UTC, cyusasnave requested changes

2024-07-07 07:35 UTC, cyusasnave commented on src/components/Forms/AddProductForm.tsx
> +				setLoading(false);
it may be better if you use try()catch()finally() to avoid the duplication of setLoading(false)

2024-07-07 07:35 UTC, cyusasnave commented on src/components/Forms/AddProductForm.tsx
> +				setLoading(false);
remove this also

2024-07-07 07:35 UTC, cyusasnave commented on src/components/Forms/AddProductForm.tsx
> +			setLoading(false);
also here

2024-07-07 07:35 UTC, cyusasnave commented on src/components/Forms/AddProductForm.tsx
> +						url={null}
Why removing the cancel button? it's a  part of the UI

2024-07-08 06:54 UTC, cyusasnave approved these changes

2024-07-08 08:51 UTC, leandreAlly approved these changes

2024-07-08 08:52 UTC, merged