#187919289 Implement statistics on seller dashboard
atlp-rwanda/hackers-ec-Fe pull request #41
Opened 2024-07-12 08:24 UTC by cyusasnave

When a seller navigates to his/her dashboard, he/she should be able to see the stats.

### How to test it?
- Clone the repo and cd into it
- checkout to feat-seller-statistics-187919289 and run npm install
- Then login as a seller then navigate to /dashboard

### Pivot tracker Id
#187919289

2024-07-16 08:51 UTC, YvetteNyibuka approved these changes

2024-07-16 09:24 UTC, YvetteNyibuka approved these changes

2024-07-16 11:30 UTC, GarrixA requested changes
<img width="1680" alt="Screenshot 2024-07-16 at 12 47 05" src="https://github.com/user-attachments/assets/9623c3c0-ce9b-4297-9faf-ca95d253bd20">

When product is expired it is behaving that way, and we are calculating number of products in RWF :|!

2024-07-16 12:57 UTC, GarrixA approved these changes

2024-07-17 13:34 UTC, leandreAlly approved these changes

2024-07-17 13:34 UTC, merged