fix(landing-page):guest shall see landing page
atlp-rwanda/hackers-ec-Fe pull request #49
Opened 2024-07-23 15:31 UTC by Tuyisenge2

How should this be manually tested?
Clone the repo and cd into it
Checkout to fix-landing-page and run npm install
Run npm run dev to start the application locally
navigate to landing page as guest , dont login

2024-07-23 16:48 UTC, GarrixA requested changes

2024-07-23 16:48 UTC, GarrixA commented on src/pages/LandingProduct.tsx
> +	//const [wishes, setWishes] = useState<DynamicData[]>([]);
Remove this comments

2024-07-23 16:48 UTC, GarrixA commented on src/pages/LandingProduct.tsx
> +	// useEffect(() => {
Also these

2024-07-23 16:48 UTC, GarrixA commented on src/pages/LandingProduct.tsx
<img width="714" alt="Screenshot 2024-07-23 at 18 43 11" src="https://github.com/user-attachments/assets/634b0f4c-f061-4932-ae93-4205a5728ecb">
<img width="522" alt="Screenshot 2024-07-23 at 18 38 38" src="https://github.com/user-attachments/assets/e2221d16-bc5d-46a1-a5e0-fb0cb14cddb4">


This page does not look well

2024-07-23 16:59 UTC, Tuyisenge2 commented on src/pages/LandingProduct.tsx
@GarrixA  I managed to make it better now

2024-07-23 19:56 UTC, GarrixA approved these changes

2024-07-24 10:25 UTC, YvetteNyibuka approved these changes

2024-07-24 10:31 UTC, leandreAlly approved these changes

2024-07-24 10:31 UTC, merged