[FIX]: Fixed the seller products page
atlp-rwanda/hackers-ec-Fe pull request #60
Opened 2024-07-26 17:34 UTC by cyusasnave

Fixed the the products page on the dashboard

2024-07-28 21:19 UTC, Hakizimana-Clement requested changes
Everything is working well, but I have some suggestions to improve the user experience on the seller dashboard:

1. Use a single loader across the  dashboard sidebar. like on dashboard have different loader, try to use loader used on products, categories, sales, and the wishlist to make a more consistent look.

2. Center the loader on the categories page.

3. On the sales page, display amessage like "Your sales are empty" when there is no sales data

![display no sales page](https://github.com/user-attachments/assets/e0a0e619-6b96-4d41-8c4a-d0aaccd9ac5e)

2024-07-29 07:06 UTC, GarrixA requested changes

2024-07-29 07:06 UTC, GarrixA commented on test/pages/LandingProduct.test.tsx
> +		// expect(name).toBeDefined();
Remove this comment

2024-07-29 08:36 UTC, Hakizimana-Clement approved these changes

2024-07-29 09:17 UTC, GarrixA approved these changes

2024-07-29 09:22 UTC, Tuyisenge2 approved these changes

2024-07-29 10:23 UTC, leandreAlly approved these changes

2024-07-29 10:24 UTC, merged