feat(fix-review):use add only one review
atlp-rwanda/hackers-ec-Fe pull request #61
Opened 2024-07-27 19:49 UTC by Tuyisenge2

what does this PR do?
user can only  add review once on product 

how to test this PR?
-clone this repository 
-install all package by run npm install and start server by  npm run dev
-login as buyer 
-buy product and try  to add review by clicking submit review more than one times

2024-07-28 21:54 UTC, Hakizimana-Clement requested changes
Everything is working well, but i have simple suggestion, you can add cursor hover on start which make it look awesome.

Here how you can do it but you can make it better than this
```
					<div
						className="text-[2rem] flex justify-center  hover:cursor-pointer"
						data-testid="rate-button"
					>
```

![Uploading add cursor point.png…]()

2024-07-29 09:39 UTC, GarrixA approved these changes

2024-07-29 10:01 UTC, Hakizimana-Clement approved these changes

2024-07-29 11:06 UTC, leandreAlly approved these changes

2024-07-29 11:06 UTC, merged