[FIX]: Check user role before dispatching cart
atlp-rwanda/hackers-ec-Fe pull request #63
Opened 2024-07-30 19:55 UTC by Hakizimana-Clement

- Dispatch the cart only if the user role is "buyer."
- Do not dispatch the cart for users with "seller" or "admin" roles.

2024-07-31 09:22 UTC, GarrixA approved these changes

2024-07-31 18:17 UTC, Tuyisenge2 approved these changes

2024-07-31 18:17 UTC, Tuyisenge2 commented on src/components/Nav.tsx
> +			if (userData?.role === 'Buyer') {
okay i test the functionality of this product and we still have this issue on product page when is an admin logged in 
![Uploading Screenshot 2024-07-31 201457.png…]()

2024-07-31 18:21 UTC, Tuyisenge2 requested changes

2024-07-31 18:21 UTC, Tuyisenge2 commented on src/components/Nav.tsx
> +			if (userData?.role === 'Buyer') {
okay i tested the functionality of this fix and we still have this issue on product page when is an admin logged in 
![Screenshot 2024-07-31 201457](https://github.com/user-attachments/assets/e7d8ff2c-8f59-4f76-8eab-5439de7cc258)

2024-08-01 07:17 UTC, Hakizimana-Clement commented on src/components/Nav.tsx
> +			if (userData?.role === 'Buyer') {
oooh, thanks. let me fix it ASAP.

2024-08-01 07:32 UTC, kwizera-bonheur25 approved these changes

2024-08-01 08:17 UTC, Tuyisenge2 approved these changes

2024-08-01 08:26 UTC, leandreAlly approved these changes

2024-08-01 08:26 UTC, merged